{
    'name': 'Shopify',
    'version': '1.0.0',
    'category': '',
    'author': 'Odoo Mates',
    'sequence':-99,
    'summary': 'Product management system',
    'description': """Product management system""",
    'depends': [],
    'data':[],
    'demo': [],
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}